"""Streamlit interface for the RAG app."""
import logging

import streamlit as st

from src.config import DEFAULT_TOP_K, RAGError, get_secret
from src.rag import answer_question, index_document
from src.vector_store import VectorStore

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

st.set_page_config(page_title="Document Q&A (RAG)", page_icon="📄", layout="wide")

# ---------- Session state (each visitor gets their own database) ----------
if "store" not in st.session_state:
    try:
        st.session_state.store = VectorStore()
    except RAGError as e:
        st.error(str(e))
        st.stop()
st.session_state.setdefault("docs", {})       # filename -> number of chunks
st.session_state.setdefault("messages", [])   # chat history shown on screen
store = st.session_state.store


def show_sources(hits):
    with st.expander(f"📚 Sources used ({len(hits)} chunks)"):
        for rank, h in enumerate(hits, start=1):
            meta = h["metadata"]
            st.markdown(
                f"**#{rank} · {meta['source']} · chunk {meta['chunk_index']} · distance {h['distance']:.3f}**"
            )
            st.text(h["text"])


# ---------- Sidebar ----------
with st.sidebar:
    st.header("⚙️ Setup")

    st.subheader("API status")
    groq_ok = bool(get_secret("GROQ_API_KEY"))
    hf_ok = bool(get_secret("HF_TOKEN"))
    st.write(("✅" if groq_ok else "❌") + " Groq API key")
    st.write(("✅" if hf_ok else "❌") + " Hugging Face token")
    if not (groq_ok and hf_ok):
        st.warning("Add the missing key(s) in your .env file (local) or Streamlit Secrets (cloud).")

    st.divider()
    st.subheader("Document")
    uploaded = st.file_uploader("Upload a PDF, TXT or DOCX", type=["pdf", "txt", "docx"])
    process_clicked = st.button("Process document", type="primary")

    if process_clicked:
        if uploaded is None:
            st.warning("Choose a file first.")
        else:
            try:
                with st.spinner("Reading, chunking and embedding..."):
                    n_chunks = index_document(store, uploaded.name, uploaded.getvalue())
                st.session_state.docs[uploaded.name] = n_chunks
                st.success(f"Processed '{uploaded.name}' into {n_chunks} chunks.")
            except RAGError as e:
                st.error(str(e))
            except Exception:
                logger.exception("Unexpected error while processing document")
                st.error("Something unexpected went wrong while processing. Check the app logs.")

    st.divider()
    st.subheader("Retrieval settings")
    top_k = st.slider("Chunks to retrieve (top_k)", 1, 10, DEFAULT_TOP_K)
    use_threshold = st.checkbox("Ignore weak matches", help="Drops chunks that are too far from the question.")
    max_distance = st.slider(
        "Max distance", 0.2, 1.5, 0.8, 0.05,
        disabled=not use_threshold,
        help="Lower = stricter. Compare the distances shown under 'Sources used' to pick a value.",
    )

    st.divider()
    if st.button("🗑️ Clear database & chat"):
        try:
            store.reset()
        except RAGError as e:
            st.error(str(e))
        st.session_state.docs = {}
        st.session_state.messages = []
        st.rerun()

# ---------- Main page ----------
st.title("📄 Document Q&A with RAG")
st.write(
    "Upload a document, process it, then ask questions. Answers are generated by a Groq-hosted LLM "
    "using only the most relevant parts of your document, retrieved from ChromaDB."
)

if st.session_state.docs:
    names = ", ".join(f"**{n}** ({c} chunks)" for n, c in st.session_state.docs.items())
    st.success(f"Ready: {names}")
else:
    st.info("No document processed yet. Upload a file in the sidebar and click **Process document**.")

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg.get("hits"):
            show_sources(msg["hits"])

question = st.chat_input(
    "Ask a question about your documents...",
    disabled=not st.session_state.docs,
)

if question:
    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)

    with st.chat_message("assistant"):
        try:
            with st.spinner("Searching your documents..."):
                result = answer_question(
                    question, store, top_k=top_k,
                    max_distance=max_distance if use_threshold else None,
                )
            st.markdown(result["answer"])
            if result["hits"]:
                show_sources(result["hits"])
            st.session_state.messages.append(
                {"role": "assistant", "content": result["answer"], "hits": result["hits"]}
            )
        except RAGError as e:
            st.error(str(e))
        except Exception:
            logger.exception("Unexpected error while answering")
            st.error("Something unexpected went wrong. Check the app logs and try again.")